### PR TITLE
Make Avram a real dependency

### LINKED ISSUE #68: avram require even though none of the code uses Avram
Avram is listed as a development dependency but it's still required in the main code. This causes problems in the effort to remove the avram dependency from Lucky since authentic is only working because it is transitive.

https://github.com/luckyframework/authentic/blob/44649db8a0a63b31b7b8065453a320e03b4eba89/shard.yml#L20-L22

https://github.com/luckyframework/authentic/blob/44649db8a0a63b31b7b8065453a320e03b4eba89/src/authentic.cr#L3

### PR DESCRIPTION
**Pull request by matthewmcgarvey**
Fixes #68

### CODE REVIEW

**Comment by jwoertink** [comment]
I'm not sure I understand this one 🤔  You can't use Authentic without Avram, so we have to ensure Avram is required before Authentic. If someone removes Avram, but left Authentic, that would break things. Maybe Avram should be a regular dependency instead of dev dependency?

**Comment by matthewmcgarvey** [comment]
None of the code in authentic is actually dependent on Avram, though. It just plays a part in the large context. Also, the lucky website uses authentic without Avram. Not too sure why it is, but I had issues when trying to remove it.

**Comment by jwoertink** [comment]
This method requires Avram

https://github.com/luckyframework/authentic/blob/44649db8a0a63b31b7b8065453a320e03b4eba89/src/authentic.cr#L117-L119

which is used in the SignUpUser operation

https://github.com/luckyframework/lucky_cli/blob/522c046f6cc3306c416a5c5175d589d5fd8bc682/src/base_authentication_app_skeleton/src/operations/sign_up_user.cr#L10-L13

As for the website, I think we actually left it in there as a safety net. We would use the website as our app to catch anything we may have broken. I'm cool with removing it though. I have a separate project started that will be better suited for that sort of thing.

**Comment by matthewmcgarvey** [comment]
@jwoertink good find! I don't know why I didn't see that method before. I went ahead and updated this PR to move avram to a full-fledged dependency

**Review by jwoertink — APPROVED** [review]
Nice. Yeah, I think this makes more sense. It'll be a slight pain when releasing Avram, and then having to do this one too, but I think it makes the most sense.

**Pull request merged**
